locals = {
  bastion_autoscaling_group_ids     = ["${aws_autoscaling_group.bastions-daudcluster-com.id}"]
  bastion_security_group_ids        = ["${aws_security_group.bastion-daudcluster-com.id}"]
  bastions_role_arn                 = "${aws_iam_role.bastions-daudcluster-com.arn}"
  bastions_role_name                = "${aws_iam_role.bastions-daudcluster-com.name}"
  cluster_name                      = "daudcluster.com"
  master_autoscaling_group_ids      = ["${aws_autoscaling_group.master-eu-west-1a-masters-daudcluster-com.id}", "${aws_autoscaling_group.master-eu-west-1b-masters-daudcluster-com.id}", "${aws_autoscaling_group.master-eu-west-1c-masters-daudcluster-com.id}"]
  master_security_group_ids         = ["${aws_security_group.masters-daudcluster-com.id}"]
  masters_role_arn                  = "${aws_iam_role.masters-daudcluster-com.arn}"
  masters_role_name                 = "${aws_iam_role.masters-daudcluster-com.name}"
  node_autoscaling_group_ids        = ["${aws_autoscaling_group.nodes-daudcluster-com.id}"]
  node_security_group_ids           = ["${aws_security_group.nodes-daudcluster-com.id}"]
  node_subnet_ids                   = ["${aws_subnet.eu-west-1a-daudcluster-com.id}", "${aws_subnet.eu-west-1b-daudcluster-com.id}", "${aws_subnet.eu-west-1c-daudcluster-com.id}"]
  nodes_role_arn                    = "${aws_iam_role.nodes-daudcluster-com.arn}"
  nodes_role_name                   = "${aws_iam_role.nodes-daudcluster-com.name}"
  region                            = "eu-west-1"
  route_table_private-eu-west-1a_id = "${aws_route_table.private-eu-west-1a-daudcluster-com.id}"
  route_table_private-eu-west-1b_id = "${aws_route_table.private-eu-west-1b-daudcluster-com.id}"
  route_table_private-eu-west-1c_id = "${aws_route_table.private-eu-west-1c-daudcluster-com.id}"
  route_table_public_id             = "${aws_route_table.daudcluster-com.id}"
  subnet_eu-west-1a_id              = "${aws_subnet.eu-west-1a-daudcluster-com.id}"
  subnet_eu-west-1b_id              = "${aws_subnet.eu-west-1b-daudcluster-com.id}"
  subnet_eu-west-1c_id              = "${aws_subnet.eu-west-1c-daudcluster-com.id}"
  subnet_utility-eu-west-1a_id      = "${aws_subnet.utility-eu-west-1a-daudcluster-com.id}"
  subnet_utility-eu-west-1b_id      = "${aws_subnet.utility-eu-west-1b-daudcluster-com.id}"
  subnet_utility-eu-west-1c_id      = "${aws_subnet.utility-eu-west-1c-daudcluster-com.id}"
  vpc_cidr_block                    = "${aws_vpc.daudcluster-com.cidr_block}"
  vpc_id                            = "${aws_vpc.daudcluster-com.id}"
}